# -*- coding: utf-8 -*-
"""Teste_Python_SummerNavi_Isabela_Barbosa

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bI9wfAslLJdyqgmqWU435o4qj6veNejP
"""

#Teste Python Summer Navi Isabela Almeida Dias Barbosa

#Exercício 1
cont = 0
for i in range(1, 5000000):
    if i % 2 == 0 and i % 49 == 0 and i % 37 == 0:
        cont += 1

print (cont)

#Exercício 2
import math
    
vetor = []
maior = 0
soma = 0
e = 2.71828182

for i in range(0,10):
    
    if i % 2 == 0 or i == 0:
        formula = (3 ** i) + 7 * (math.factorial(i))
    else:
        formula = (2 ** i) + 4 * math.log(i, e)

    vetor.append(formula)
    soma = soma + vetor[i]

val_max = max(vetor)

vetor_pos = vetor.index(val_max)

qtde = len(vetor)

#Posição do elemento maior
print(vetor_pos)

#Média dos valores do vetor
print(round((soma/qtde),2))

#Exercício 3
Nome = ["A", "B", "C", "D" ,"E"]
lista_notas = []

for i in range(0,5):
    Nota = float(input(""))    
    lista_notas.append(Nota)

lista = [(lista_notas[0],Nome[0]), (lista_notas[1],Nome[1]),(lista_notas[2],Nome[2]),(lista_notas[3],Nome[3]),(lista_notas[4],Nome[4])]

dicio = dict(lista)

Max = max(lista_notas)

print(dicio.get(Max))

print(Max)